### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by cmungall** [alliance-genome/agr_prototype#3]
Even though this is a prototype it's a good idea to have this file for this and all repos, just to clarify to other AGR members how they can contribute if they want to. E.g. I assume the preferred method of contribution from the non-leads is PRs.

**Comment by ragingsquirrel3** [comment]
sure, that makes sense.  I created a development branch, and I think people should make their PRs to and from the development branch.  The CONTRIBUTING.md can describe this further.

**Comment by ragingsquirrel3** [comment]
https://github.com/alliance-genome/agr_prototype/blob/master/CONTRIBUTING.md
