### ISSUE TITLE
Synonum List for Zebrafish genes is incorrect

### ISSUE THREAD

**Issue by cmpich** [alliance-genome/agr_prototype#41]
When searching for fgf8a you get back the zebrafish gene 'fgf8a'  but in the synonym line there are bogus entries of ZFIN internal IDs:
synonyms: ,ZDB-GENE-990415-72,ZDB-GENE-990415-72,ace,ZDB-DALIAS-020718-220,fgf-8,ZDB-DALIAS-020718-260,cb110,ZDB-DALIAS-030131-10120,wu:fb73a06,ZDB-DALIAS-040625-5,fgf8,ZDB-DALIAS-070724-13,etID309886.13,ZDB-DALIAS-050728-213,id:ibd5031,ZDB-DALIAS-040625-4,acerebellar,ZDB-DALIAS-070117-777,ZDB-GENE-010319-21,ZDB-GENE-030131-1493,ZDB-LOCUS-990215-13

All the ZDB-<xxx> entries should not be there.

**Comment by cmpich** [comment]
It's most likely a problem with the query to zebrafishmine. Will modify the query to suppress internal id's.

**Comment by pedrohr** [comment]
Data from new query indexed. Looks ok now.

Could you please validate so we can close the issue?

**Comment by gabinkley** [comment]
From Sierra: "I think we can close this"
