### ISSUE TITLE
Add necessary data for chromosome and genomic coordinates 

### ISSUE THREAD

**Issue by ragingsquirrel3** [alliance-genome/agr_prototype#44]
The search response items for gene category lack the necessary data to render relative and genomic coordinates.

**Comment by gabinkley** [comment]
Perhaps just need genomic (chromosomal) coordinate - not relative coordinates.

**Comment by ragingsquirrel3** [comment]
Ok, then the response needs the chromosome name/number.

**Comment by gabinkley** [comment]
See #37 5)
