### ISSUE TITLE
Add GO synonyms

### ISSUE THREAD

**Issue by gabinkley** [alliance-genome/agr_prototype#47]
Need to add GO synonyms to go results

**Comment by gabinkley** [comment]
See #37 4) and 6)

**Comment by pedrohr** [comment]
The data is indexed. Although we need more clarification on how to display the data. Should we do anything with the categories of synonyms (eg. EXACT, BROAD, NARROW, RELATED, etc) ?

**Comment by chris-grove** [comment]
@pedrohr  I suggested in the use case document:

https://docs.google.com/document/d/1M8bNyH_MIc1fHrrPJdn8AtgedvzP8pWboP1uTKejVNQ/edit

that we just focus on EXACT synonyms for now.

**Comment by pedrohr** [comment]
Thanks Chris! Sorry I totally missed that. I will filter them out.

**Comment by chris-grove** [comment]
@pedrohr 
No problem, it wasn't in the original version; I had added it a bit later

**Comment by pedrohr** [comment]
They are filtered and indexed.

Closing.
