### ISSUE TITLE
incorporate immutable.js

### ISSUE THREAD

**Issue by ragingsquirrel3** [alliance-genome/agr_prototype#5]

**Comment by ragingsquirrel3** [comment]
incorporate https://facebook.github.io/immutable-js/ into redux stores

**Comment by ragingsquirrel3** [comment]
The only business logic in reducers so far is the block around https://github.com/alliance-genome/agr_prototype/blob/master/src/js_src/reducers/searchReducer.js#L30.  If anyone has experience with immutable and wants to make a PR for it, that would be great.

**Comment by jogoodma** [comment]
I started one here https://github.com/FlyBase/agr_prototype/commit/7f4bffdf01955513d719c55d77d5977057a65cb5.  I broke the test suite, so I need to figure out what I did before I do a PR.

**Comment by ragingsquirrel3** [comment]
Thanks for the start.  It's looking good.  I'll try to have a look, and I'm also open to different testing strategies.  The existing js unit tests are kind of sanity checks "this should be able to convert to HTML," and hopefully we can add more robust tests for reducers.

**Comment by ragingsquirrel3** [comment]
I checkout out this fork and got the tests passing on a branch I added to this repo called "immutable_fixes," however it's throwing errors when I actually run it, and it has something to do with selectors not returning what the component expects.  The search component is expecting results to be of type array.

In https://github.com/alliance-genome/agr_prototype/blob/immutable_fixes/src/js_src/containers/search/filterSelector.js#L79

but I don't have much experience with selectors, so maybe this kind of code, as well as a similar method at https://github.com/alliance-genome/agr_prototype/blob/immutable_fixes/src/js_src/containers/search/index.js#L143 should be done the same way

I'm not sure if that's helpful.

**Comment by ragingsquirrel3** [comment]
Interestingly, in the test env (node.js) it converts to array just fine, but in my browser the results passed to the search component is of type function.

**Comment by ragingsquirrel3** [comment]
ahh, just realized results is array in the test env bc it's defined as an array which will override what comes from redux https://github.com/alliance-genome/agr_prototype/blob/immutable_fixes/src/js_src/containers/search/test.js#L17

maybe if that `results={[]}`is removed from test then it will reproduce the issue in test env

**Comment by jogoodma** [comment]
I've done a few more [edits](https://github.com/FlyBase/agr_prototype/commit/d3bd533573c93571f8eb338e7e3e6218760f8b93) and added some unit tests for the selectors.  All but one of your tests are validating now.  Something is causing the [renderFilters](https://github.com/FlyBase/agr_prototype/blob/master/src/js_src/containers/search/filterSelector.js#L34) function to not receive the proper props it expects.  It isn't clear to me why.

The fact that I can't get the full Makefile build to run properly is further complicating my debugging.  The Makefile keeps choking on the python parts and bails out.  It looks like pip is trying to install in the system area and getting denied.  I haven't gone any further than a cursory look at the Makefile output.

**Comment by ragingsquirrel3** [comment]
Thanks, I'll try to have a look.  The python stuff sounds frustrating, but I would recommend setting up http://docs.python-guide.org/en/latest/dev/virtualenvs/ for the python dep problems..

**Comment by jogoodma** [comment]
I think we are all set now.  The issue had to do with how I was using the selectors and differences between this setup and the one I generally work in (react-boilerplate).

**Comment by ragingsquirrel3** [comment]
merged into master and on http://alliancegenome.org:5000/. refinements can be new issue.  Thanks @jogoodma
