### ISSUE TITLE
Show GO ids in Table view

### ISSUE THREAD

**Issue by gabinkley** [alliance-genome/agr_prototype#51]
From Chris Grove: As for GO IDs, they still are not showing up in the table view, as far as I can tell. They only display in the list view.

**Comment by ragingsquirrel3** [comment]
They were intentionally omitted based on the initial use case, but can easily be added to the table.  Should they be?

**Comment by chris-grove** [comment]
@ragingsquirrel3 
Yes, please. They were requested in point 3c of the use case:

https://docs.google.com/document/d/1M8bNyH_MIc1fHrrPJdn8AtgedvzP8pWboP1uTKejVNQ/edit

At the time of writing the use case, we didn't specify a distinct view for list or table view as we didn't think/know we would have two different views, so we were just asking to display the GO ID in general. I think what we had in mind was to display the IDs in a table view.

**Comment by ragingsquirrel3** [comment]
Cool, I'll incorporate.  Thanks

**Comment by ragingsquirrel3** [comment]
http://search.alliancegenome.org/search?category=go&mode=table&q=brain

**Comment by chris-grove** [comment]
Looks good! Thanks!
